apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app2
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: app2
    spec:
      containers:
        - image: app-ms2-product
          name: app-ms2-product
          ports:
            - containerPort: 9091
          resources: {}
      restartPolicy: Always
status: {}
