global:
  scrape_interval:     10s 
  evaluation_interval: 10s 

scrape_configs:
  - job_name: app-ms1-user
    scrape_interval: 1s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app-ms1-user:9192']